
---------------------------------- 1.AVERAGE ORDER VALUE (AOV) -------------------------------------------------------------

SELECT (SUM(PRICE * QUANTITY) / SUM(QUANTITY))  AS [AVERAGE ORDER VALUE] FROM YEAR_9_10



-------------------------------- 2. CUSTOMER LIFETIME VALUE(CLV) ---------------------------------------------------------

-- STEP 1: CALCULATE AVERAGE PURCHASE VALUE
SELECT 
    AVG(PRICE) AS AVG_PURCHASE_VALUE 
FROM 
    (
        SELECT 
            CUSTOMER_ID, 
            SUM(PRICE * QUANTITY) AS TOTAL_SPENT 
        FROM 
            YEAR_9_10 
        GROUP BY 
            CUSTOMER_ID
    ) AS PURCHASES;

-- STEP 2: CALCULATE PURCHASE FREQUENCY
SELECT 
    COUNT(*) / COUNT(DISTINCT CUSTOMER_ID) AS PURCHASE_FREQUENCY 
FROM 
    YEAR_9_10;

-- STEP 3: CALCULATE CUSTOMER LIFESPAN
SELECT 
    DATEDIFF(MAX(INVOICEDATE), MIN(INVOICEDATE)) AS CUSTOMER_LIFESPAN 
FROM 
    YEAR_9_10;

-- STEP 4: COMBINE VALUES TO CALCULATE CLV
SELECT 
    (SELECT AVG(PRICE) FROM (SELECT CUSTOMER_ID, SUM(PRICE * QUANTITY) AS TOTAL_SPENT FROM YEAR_9_10 GROUP BY CUSTOMERID) AS PURCHASES) * 
    (SELECT COUNT(*) / COUNT(DISTINCT CUSTOMERID) FROM YEAR_9_10) * 
    (SELECT DATEDIFF(MAX(INVOICEDATE), MIN(INVOICEDATE)) FROM YEAR_9_10) AS CLV;




---------------------------------- 3. REPEAT PURCHASE RATE -----------------------------------------------------

SELECT (COUNT(DISTINCT REPEAT_CUSTOMER_ID) / COUNT(CUSTOMER_ID)) * 100 AS [REPEAT PURCAHSE RATE]
FROM YEAR_9_10 AS A 
LEFT JOIN  (
			SELECT CUSTOMER_ID AS REPEAT_CUSTOMER_ID, COUNT(CUSTOMER_ID)  AS REPEATS FROM YEAR_9_10
			GROUP BY CUSTOMER_ID
			HAVING COUNT(CUSTOMER_ID) > 1

	) B ON A.CUSTOMER_ID = B.REPEAT_CUSTOMER_ID
WHERE CUSTOMER_ID IS NOT NULL




------------------------------------ 4. CHURN RATE ---------------------------------------------------------------

SELECT (COUNT(DISTINCT REPEAT_CUSTOMER_ID) / COUNT(CUSTOMER_ID)) * 100 AS [CHURN RATE]
FROM YEAR_9_10 AS A 
LEFT JOIN  (
			SELECT CUSTOMER_ID AS REPEAT_CUSTOMER_ID, COUNT(CUSTOMER_ID)  AS REPEATS FROM YEAR_9_10
			GROUP BY CUSTOMER_ID
			HAVING COUNT(CUSTOMER_ID) = 1

	) B ON A.CUSTOMER_ID = B.REPEAT_CUSTOMER_ID
WHERE CUSTOMER_ID IS NOT NULL